services:
  db:
    image: mysql:8.4.0
    restart: always
    command: ["mysqld", "--mysql-native-password=ON"]
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=typeorm
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
