services:
  db:
    image: mysql:8.4.0
    restart: always
    command: ["mysqld", "--mysql-native-password=ON"]
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=typeorm
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - '3000:3000'
    environment:
      - DB_TYPE=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_HOST=db
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=typeorm
    depends_on:
      - db   
    volumes:
      - /app/node_modules
      - .:/app
